### ISSUE TITLE
统计表单结果的问题

### ISSUE THREAD

**Issue by Tialon** [flute/formbuilder#1]
问一下，表单发放给用户，进行结果统计作者这边有方法吗，我这边在用你的东西。目前的打算是将结果转换成ABCD这样的结果，再按照每个题目进行统计，作者之前有解决方案吗？

**Comment by flute** [comment]
@libingyu 
这个组件只是来实现快速生成表单，做结果统计的话，主要是你的数据库结构有关，设计合理的数据表，存储问卷、答案、选项，就可以统计每个问卷每道题的答案占比这些。
